import { writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { AppManifest, AppNavigation } from '@maia/shared'
import type { ProviderRegistry } from '../llm/ProviderRegistry'
import { pino } from 'pino'

const logger = pino({ name: 'manifest-generator' })

/**
 * Generates app manifests using LLM knowledge when a user installs a custom URL app
 * that doesn't have a pre-built manifest. The LLM knows how most popular web apps work
 * and can produce navigation guides + behavioral rules on the fly.
 */
export class ManifestGenerator {
  private readonly llm: ProviderRegistry
  private readonly manifestDir: string

  constructor(llm: ProviderRegistry, manifestDir: string) {
    this.llm = llm
    this.manifestDir = manifestDir
  }

  /**
   * Generate a manifest for a custom app. If the LLM recognizes the app,
   * it produces a detailed guide. If not, it produces generic rules.
   */
  async generate(url: string, name: string): Promise<AppManifest> {
    const hostname = extractHostname(url)
    const manifestId = hostname.replace(/\./g, '-')

    logger.info({ url, name, hostname }, 'Generating manifest for custom app')

    try {
      const response = await this.llm.sendMessage([
        {
          role: 'system',
          content: `you generate navigation guides for web apps. you know how most popular web apps work from your training data.

given a URL and app name, produce a YAML manifest with:
1. overview: what the app does (2-3 sentences)
2. pages: the main pages/views with their layout and key interactive elements
3. workflows: step-by-step instructions for common tasks (3-5 workflows)
4. rules: 5-10 behavioral rules the AI agent MUST follow when using this app
5. tips: 3-5 tips for using the app effectively

RULES MUST INCLUDE:
- "NEVER try to search the web from inside this app. This app is for [purpose] only."
- any actions that need user approval (payments, sending messages, deleting data, posting publicly)
- how to navigate the app (sidebar, tabs, search)
- how to interact with key elements (click, type, select)

respond with ONLY the YAML content inside the navigation: block. no other text.
if you don't know the app well, still produce reasonable generic rules based on the URL and name.

example format:
overview: >
  App description here.
pages:
  main:
    description: "Main view"
    layout:
      - "Top: navigation bar"
      - "Center: main content"
workflows:
  basic_task:
    - "Step 1"
    - "Step 2"
rules:
  - "Rule 1"
  - "Rule 2"
tips:
  - "Tip 1"`,
        },
        { role: 'user', content: `Generate a navigation guide for:\nApp name: ${name}\nURL: ${url}\nDomain: ${hostname}` },
      ], { maxTokens: 2048, temperature: 0.3 })

      const navigation = parseNavigationYaml(response.content)

      const manifest: AppManifest = {
        name,
        id: manifestId,
        icon: '🌐',
        url,
        category: 'other',
        aiDescription: navigation?.overview as string ?? `${name} web app`,
        navigation,
        helpUrl: undefined,
      }

      // Save to disk so it persists across restarts
      await this.saveManifest(manifestId, manifest, response.content)

      logger.info({ manifestId, name }, 'Generated and saved manifest for custom app')
      return manifest
    } catch (error) {
      logger.warn({ url, name, error }, 'Failed to generate manifest, using fallback')
      return this.fallbackManifest(url, name, manifestId)
    }
  }

  private async saveManifest(manifestId: string, manifest: AppManifest, rawNavigation: string): Promise<void> {
    const yamlContent = `# Auto-generated manifest for ${manifest.name}
# Generated by Maia AI — review and edit as needed
name: ${manifest.name}
id: ${manifestId}
icon: "${manifest.icon}"
url: ${manifest.url}
category: ${manifest.category}
ai_description: "${manifest.aiDescription}"

navigation:
${indent(rawNavigation, 2)}
`

    const filePath = join(this.manifestDir, `${manifestId}.yml`)
    try {
      await writeFile(filePath, yamlContent, 'utf-8')
      logger.info({ filePath }, 'Saved generated manifest')
    } catch (error) {
      logger.warn({ filePath, error }, 'Failed to save manifest to disk')
    }
  }

  private fallbackManifest(url: string, name: string, manifestId: string): AppManifest {
    return {
      name,
      id: manifestId,
      icon: '🌐',
      url,
      category: 'other',
      aiDescription: `${name} web app at ${url}`,
      navigation: {
        overview: `${name} — a web application. No detailed navigation guide available. Use general web browsing skills.`,
        rules: [
          'NEVER try to search the web from inside this app.',
          'Look for a navigation bar, sidebar, or menu to explore the app.',
          'Look for search functionality within the app to find content.',
          'Click buttons and links by their visible text.',
          'Scroll down to see all content on long pages.',
          'If the app requires login, report to the user and stop.',
          'Do NOT make purchases, send messages, or delete data without explicit user approval.',
          'If you get stuck, describe what you see in the team chat and ask for guidance.',
        ],
        tips: [
          'Most web apps have a top navigation bar or left sidebar for main sections.',
          'Look for a search icon or search bar to find specific content.',
          'Keyboard shortcuts like Cmd+F can help find text on the page.',
        ],
      },
      helpUrl: undefined,
    }
  }
}

function extractHostname(url: string): string {
  try {
    return new URL(url).hostname.replace('www.', '')
  } catch {
    return url.replace(/https?:\/\//, '').split('/')[0] ?? url
  }
}

function parseNavigationYaml(content: string): AppNavigation | undefined {
  try {
    // The LLM returns YAML content — try to parse it
    const { parse } = require('yaml') as { parse: (s: string) => unknown }

    // Strip markdown code fences if present
    const cleaned = content
      .replace(/^```ya?ml\n?/m, '')
      .replace(/\n?```$/m, '')
      .trim()

    const parsed = parse(cleaned) as Record<string, unknown>

    // The response might be the navigation block directly, or wrapped
    if (parsed.navigation) return parsed.navigation as AppNavigation
    if (parsed.overview || parsed.pages || parsed.rules) return parsed as AppNavigation
    return undefined
  } catch {
    return undefined
  }
}

function indent(text: string, spaces: number): string {
  const pad = ' '.repeat(spaces)
  return text.split('\n').map((line) => line.trim() ? pad + line : line).join('\n')
}
